### ISSUE TITLE
+1,同样的问题

### ISSUE THREAD

**Issue by BAS27-BKK** [SideStore/sidestore.github.io#20]
![0b043ce02728e7a323dea7e27344bba6](https://user-images.githubusercontent.com/125727261/229261717-0cce85a3-d38d-46ca-8e5b-3669d41e9c60.png)
![ios-15-128x128_2x](https://user-images.githubusercontent.com/125727261/229261719-c848a050-44a4-41f8-834b-c024eb87ecb5.png)
![palera1nicon](https://user-images.githubusercontent.com/125727261/229261720-1d42bf1c-94e8-44a5-b4f5-57d00fb516d6.png)
![image00001](https://user-images.githubusercontent.com/125727261/229261722-f4bb5acc-c9a5-4d39-87d5-8c4310c43423.png)
              +1,同样的问题

_Originally posted by @yangy666 in https://github.com/SideStore/SideStore/issues/320#issuecomment-1489552984_

**Comment by naturecodevoid** [comment]
???

**Comment by Spidy123222** [comment]
Unrelated to website.
