### ISSUE TITLE
 Can't install because of an error

### ISSUE THREAD

**Issue by mnfari** [SideStore/sidestore.github.io#33]
ssl error winhttp_callback_status_flag_cert_REV_failed failed to check revocation status
I tried restarting my computer but it didn't work and when I looked at it in altstore reddit, they said I should do a proxy but idk how.
![Screenshot 2023-11-30 084204](https://github.com/SideStore/sidestore.github.io/assets/84629171/ad1c3a95-519a-4178-a130-308032578405)

**Comment by WesleyBryie** [comment]
This is the website's github repo.

- Please follow the instructions at [https://wiki.sidestore.io/](https://wiki.sidestore.io/).
- Please consider making an issue at [https://github.com/sidestore/sidestore](https://github.com/sidestore/sidestore) or joining the Discord server at [https://discord.gg/sidestore-949183273383395328](https://discord.gg/sidestore-949183273383395328)
