### ISSUE TITLE
can't install for this error please help

### ISSUE THREAD

**Issue by Palucaz** [SideStore/sidestore.github.io#35]
The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

**Comment by Spidy123222** [comment]
Please read the sidestore repo issues. Especially the completed ones. The this is only the repo for the website. https://github.com/SideStore/SideStore
