### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by AresTheKing** [SideStore/sidestore.github.io#60]
Im trying to login into the Sidestore app with my apple id and it's not working. I followed all the steps correctly

**Comment by AresTheKing** [comment]
How do I use the code in Sidestore. Its not asking for a code. Its not letting me login at all.

**Comment by AresTheKing** [comment]
> **Dont get Verification code when signing into Sidestore?**
> 
> *For ios versions below 18.1*
> 
> 
> 
> > Go to settings
> 
> 
> 
> > Tap on your name
> 
> 
> 
> > Sign in and security
> 
> 
> 
> > Two factor authentication
> 
> 
> 
> > Get verification code
> 
> 
> 
> 
> 
> *For ios versions 18.1 and above*
> 
> > Go to <https://www.icloud.com>
> 
> 
> 
> > Press sign in
> 
> 
> 
> > You will now be greeted with 2 options ("Sign in", and "Use different apple account")
> 
> > -# select the bottom option, "Use different apple account"
> 
> 
> 
> > After putting your apple id and password, apple will send you a verification code
> 
> > -# Use that code in Sidestore

I just downloaded the app for the first time. It never asked for a code it's just not accepting my login at all. I know it

**Comment by AresTheKing** [comment]
It worked thank you

**Comment by AresTheKing** [comment]
I have a final question. I saw people talking about only being able to sideload 3 apps. Is there some king of bypass?

**Comment by AresTheKing** [comment]
I dont see disable app limit

**Comment by AresTheKing** [comment]
How do i get sparsebox to work if if its telling me I hit the limit already

**Comment by polymo1** [comment]
Not the right repo for this
