### ISSUE TITLE
Site no longer accessible

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/sidestore.github.io#9]
Too many redirects. This seemed to come up on a some recent commits. Cloudflare shouldn't be the issue.

**Comment by lonkelle** [comment]
Yeah, if I revert the most recent merge, it works again, but I don't know what's causing it in the first place. Gonna assign this to Joe since I don't know who else has access to Cloudflare.

**Comment by f1shy-dev** [comment]
The site was also rewritten in the "recent commits", which could be part of why the site isn't working.

With the new method of deploying via GITHUB actions I'm yet to confirm whether the CNAME file has to be in the deployment or in the repo root

I'll make another push to see if it fixes it

**Comment by f1shy-dev** [comment]
Update: check my PR

**Comment by f1shy-dev** [comment]
Can we close this? site is fixed for now

unless we're leaving it open for a future day to discuss fixing cloudflare??
